language: node_js
node_js: '4.0'

before_install:
  - gem update --system
  - gem install sass

script:
  - npm run all

after_success:
  - bash ./deploy.sh

env:
    global:
        - ENCRYPTION_LABEL: "65264555cfc7"
        - COMMIT_AUTHOR_EMAIL: "ca.brengesjo@gmail.com"
